platform :ios, '8.0'
target 'GouKuSeller' do
    pod 'Masonry'
    pod 'AFNetworking', '2.5.4'
    pod 'MJRefresh','2.4.7'
    pod 'Reachability'
    pod 'JPush'
    pod 'MJExtension', '2.5.5'
    pod 'MBProgressHUD'
    pod 'SDWebImage', '3.8.2'
    pod 'AMap3DMap'
    pod 'AMapSearch'
    pod 'AMapLocation'
    pod 'WechatOpenSDK'
    pod 'AliyunOSSiOS'
    pod 'Bugtags'
    pod 'UMCCommon'
    pod 'UMCAnalytics'
    pod 'UMCSecurityPlugins'
end
inhibit_all_warnings!
